import { Inter, Onest } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({subsets: ["latin"]});

const onest = Onest({
  weight:["300" , "400" , "500" , "600" , "700" , "800" , "900" ],
  style: ["normal"],
  subsets: ["latin"],
  display:"swap",
})


export const metadata = {
  title: "Artist-web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{
      "--ff-onest":onest.style.fontFamily,
    }} >
      <body className={onest.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
